// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 rituparnaprof
// SecuredStorage - macOS Native Touch ID & LocalAuthentication Bridge

#import <Foundation/Foundation.h>
#import <LocalAuthentication/LocalAuthentication.h>
#import <AppKit/AppKit.h>

/**
 * Write UTF-8 string to macOS general pasteboard with strict secrecy and transient anti-cloud flags:
 * - org.nspasteboard.ConcealedType: Instructs clipboard history managers (Alfred, Raycast, Maccy, Paste) NOT to record this entry
 * - org.nspasteboard.TransientType: Suppresses Apple Universal Clipboard & Continuity Handoff from syncing over iCloud/Bluetooth
 * - org.nspasteboard.AutoGeneratedType: Flags as auto-generated sensitive credential
 * Returns the current changeCount of the pasteboard after writing.
 */
long write_concealed_macos_pasteboard(const char* utf8_text) {
    @autoreleasepool {
        NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
        [pasteboard clearContents];

        if (!utf8_text) {
            return (long)[pasteboard changeCount];
        }

        NSString *string = [NSString stringWithUTF8String:utf8_text];
        NSPasteboardItem *item = [[NSPasteboardItem alloc] init];
        [item setString:string forType:NSPasteboardTypeString];

        // 1. Concealed Type (History Suppressor for Alfred, Raycast, Maccy, Paste, LaunchBar)
        NSPasteboardType concealedType = @"org.nspasteboard.ConcealedType";
        [item setString:@"" forType:concealedType];

        // 2. Transient Type (Cloud Sync Suppressor for Universal Clipboard)
        NSPasteboardType transientType = @"org.nspasteboard.TransientType";
        [item setString:@"" forType:transientType];

        // 3. Auto-Generated Type
        NSPasteboardType autoGeneratedType = @"org.nspasteboard.AutoGeneratedType";
        [item setString:@"" forType:autoGeneratedType];

        [pasteboard writeObjects:@[item]];
        return (long)[pasteboard changeCount];
    }
}

/**
 * Get current changeCount of macOS pasteboard.
 */
long get_macos_pasteboard_change_count(void) {
    @autoreleasepool {
        NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
        return (long)[pasteboard changeCount];
    }
}

/**
 * Clear the macOS pasteboard only if changeCount matches the expected count
 * (ensuring we don't clear data the user copied subsequently).
 * If expected_change_count < 0, clears unconditionally.
 */
int clear_macos_pasteboard_if_matches(long expected_change_count) {
    @autoreleasepool {
        NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
        long currentCount = (long)[pasteboard changeCount];
        if (expected_change_count < 0 || currentCount == expected_change_count) {
            [pasteboard clearContents];
            return 1; // Cleared successfully
        }
        return 0; // Not cleared (user copied something else)
    }
}

/**
 * Trigger native macOS Touch ID biometric prompt
 * Returns:
 *   1 = Authentication succeeded
 *   0 = User canceled or biometric authentication failed
 *  -1 = Biometrics not supported or not enrolled on this hardware
 */
int evaluate_macos_touch_id(const char* reason_utf8) {
    @autoreleasepool {
        LAContext *context = [[LAContext alloc] init];
        NSError *error = nil;
        NSString *nsReason = [NSString stringWithUTF8String:reason_utf8];

        // Explicitly enforce zero allowable reuse duration:
        // Ensures macOS MUST prompt for the physical finger touch on every verification
        context.touchIDAuthenticationAllowableReuseDuration = 0.0;

        // First test if biometric authentication is available on this Mac
        LAPolicy policy = LAPolicyDeviceOwnerAuthenticationWithBiometrics;
        if (![context canEvaluatePolicy:policy error:&error]) {
            // Fallback to device owner authentication (system password / Apple Watch)
            policy = LAPolicyDeviceOwnerAuthentication;
            if (![context canEvaluatePolicy:policy error:&error]) {
                return -1; // Not supported or unavailable
            }
        }

        __block int authResult = 0;
        dispatch_semaphore_t sem = dispatch_semaphore_create(0);

        [context evaluatePolicy:policy
                localizedReason:nsReason
                          reply:^(BOOL success, NSError * _Nullable __unused authError) {
            (void)authError;
            if (success) {
                authResult = 1;
            } else {
                authResult = 0;
            }
            dispatch_semaphore_signal(sem);
        }];

        dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
        return authResult;
    }
}
